[package]
name = "pdtserver"
version = "0.0.1"
authors = ["Erik Källberg"]
edition = "2021"

[dependencies]
axum = "0.6.20"
tokio = { version = "1.32.0", features = ["full"] }
pdtcore = { path = "../pdtcore" }
askama = "0.12.0"
ulid = "1.1.0"